"""Bayesian recovery of nuclear spin configurations from coherence data."""

from .algorithms import (
    RJMCMC,
    RWMH,
    Algorithm,
    BirthDeathKernel,
    ParallelTempering,
    ParameterBlock,
    Target,
    geometric_ladder,
)
from .config import (
    DEFAULT_QOS,
    KNOWN_ALGORITHMS,
    PERLMUTTER_ACCOUNT,
    PERLMUTTER_WORKDIR,
    RunConfig,
    merge_run,
    run_ensemble,
    submission_script,
)
from .design import (
    CandidateDesign,
    DecouplingScaling,
    DesignResult,
    DesignUtility,
    ExpectedInformationGain,
    ExperimentDesigner,
    InformationDensity,
    NothingToLearn,
    ParticleSet,
    PointSelector,
    SequenceDuration,
    format_measurement_table,
    information_density,
    measurement_rows,
    measurement_table_html,
    write_measurement_csv,
)
from .driver import HybridDriver, Schedule, Step
from .ensemble import (
    RHAT_PARAMETERS,
    Agreement,
    EnsembleResult,
    EnsembleRunner,
    derive_seeds,
    load_ensembles,
    merge_traces,
    rhat,
    spread_across_k,
)
from .experiment import TAU_UNITS, Experiment, ExperimentSet
from .lattice import SiteTable, read_hyperfine_table, secular_components
from .neighbors import NeighborIndex
from .proposals import (
    ContinuousReflected,
    DiscreteLatticeWalk,
    GaussianOffset,
    Proposal,
    SiteScaledOffset,
)
from .likelihood import (
    GaussianL2,
    Likelihood,
    WassersteinL2,
    signal_measure,
    wasserstein_signal_distance,
)
from .forward import (
    AnalyticCCE1,
    Envelope,
    ForwardModel,
    StretchedExponential,
    single_spin_modulation,
)
from .post import (
    BANDS,
    coupling_posterior,
    MATCH_TOL,
    PosteriorSummary,
    band_index,
    by_band,
    couplings,
    detection_rate,
    false_absence,
    ModalConfiguration,
    RelaxedCouplings,
    compare_couplings,
    matches,
    modal_configuration,
    predictive_signals,
    relaxed_couplings,
    residual_distribution,
    summarize,
)
from .simulate import add_noise, simulate_coherence, simulate_dataset
from .state import State
from .trace import Trace
from .units import TWO_PI, SUPPORTED_ISOTOPES, gyromagnetic_ratio, to_angular

__all__ = [
    "Agreement",
    "Algorithm",
    "AnalyticCCE1",
    "BANDS",
    "BirthDeathKernel",
    "CandidateDesign",
    "ContinuousReflected",
    "DEFAULT_QOS",
    "DecouplingScaling",
    "DesignResult",
    "DesignUtility",
    "DiscreteLatticeWalk",
    "EnsembleResult",
    "EnsembleRunner",
    "Envelope",
    "ExpectedInformationGain",
    "Experiment",
    "ExperimentDesigner",
    "ExperimentSet",
    "ForwardModel",
    "GaussianL2",
    "GaussianOffset",
    "HybridDriver",
    "InformationDensity",
    "KNOWN_ALGORITHMS",
    "Likelihood",
    "MATCH_TOL",
    "ModalConfiguration",
    "NeighborIndex",
    "NothingToLearn",
    "PERLMUTTER_ACCOUNT",
    "PERLMUTTER_WORKDIR",
    "ParallelTempering",
    "ParameterBlock",
    "ParticleSet",
    "PointSelector",
    "PosteriorSummary",
    "Proposal",
    "RHAT_PARAMETERS",
    "RJMCMC",
    "RWMH",
    "RelaxedCouplings",
    "RunConfig",
    "SUPPORTED_ISOTOPES",
    "Schedule",
    "SequenceDuration",
    "SiteScaledOffset",
    "SiteTable",
    "State",
    "Step",
    "StretchedExponential",
    "TAU_UNITS",
    "TWO_PI",
    "Target",
    "Trace",
    "WassersteinL2",
    "add_noise",
    "band_index",
    "by_band",
    "compare_couplings",
    "coupling_posterior",
    "couplings",
    "derive_seeds",
    "detection_rate",
    "false_absence",
    "format_measurement_table",
    "geometric_ladder",
    "gyromagnetic_ratio",
    "information_density",
    "load_ensembles",
    "matches",
    "measurement_rows",
    "measurement_table_html",
    "merge_run",
    "merge_traces",
    "modal_configuration",
    "predictive_signals",
    "read_hyperfine_table",
    "relaxed_couplings",
    "residual_distribution",
    "rhat",
    "run_ensemble",
    "secular_components",
    "signal_measure",
    "simulate_coherence",
    "simulate_dataset",
    "single_spin_modulation",
    "spread_across_k",
    "submission_script",
    "summarize",
    "to_angular",
    "wasserstein_signal_distance",
    "write_measurement_csv",
]
